export const TODO_STATUS = {
  FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
  FETCH_TODOS_FAILER: 'FETCH_TODOS_FAILER',
  TOGGLE_TODOS_SUCCESS: 'TOGGLE_TODOS_SUCCESS',
  TOGGLE_TODOS_FAILER: 'TOGGLE_TODOS_FAILER',
  ADD_TODOS_SUCCESS: 'ADD_TODOS_SUCCESS',
  ADD_TODOS_FAILER: 'ADD_TODOS_FAILER',
  REMOVE_TODOS_SUCCESS: 'REMOVE_TODOS_SUCCESS',
  REMOVE_TODOS_FAILER: 'REMOVE_TODOS_FAILER',
};
